load("@rules_python//python:python.bzl", "py_library")

py_library(
    name = "utils",
    visibility = ["//visibility:public"],
    srcs = [":__init__.py", ":pyqt_import_hook.py", ":win_dll_import.py"],
)